services:
  open-crawler-service:
    build:
      context: ./crawler-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - env.local
    volumes:
      - ./crawls:/crawler/crawls

  open-crawler-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "16700:16700"
    env_file:
      - env.local
    depends_on:
      - open-crawler-service
